import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";

const notoSerifJP = localFont({
    src: "./fonts/NotoSerifJP-VariableFont_wght.ttf",
    variable: "--font-noto-serif-jp",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${notoSerifJP.variable} font-notoSerifJP`}>
                {children}
            </body>
        </html>
    );
}
